import type { ImageSourcePropType } from 'react-native';

declare const require: (path: string) => ImageSourcePropType;

export const flagSources: Record<string, ImageSourcePropType> = {
  ar: require('react-native-twemoji/twemojis/1f1e6-1f1f7.png'),
  at: require('react-native-twemoji/twemojis/1f1e6-1f1f9.png'),
  au: require('react-native-twemoji/twemojis/1f1e6-1f1fa.png'),
  ba: require('react-native-twemoji/twemojis/1f1e7-1f1e6.png'),
  be: require('react-native-twemoji/twemojis/1f1e7-1f1ea.png'),
  br: require('react-native-twemoji/twemojis/1f1e7-1f1f7.png'),
  ca: require('react-native-twemoji/twemojis/1f1e8-1f1e6.png'),
  cd: require('react-native-twemoji/twemojis/1f1e8-1f1e9.png'),
  ch: require('react-native-twemoji/twemojis/1f1e8-1f1ed.png'),
  ci: require('react-native-twemoji/twemojis/1f1e8-1f1ee.png'),
  co: require('react-native-twemoji/twemojis/1f1e8-1f1f4.png'),
  cv: require('react-native-twemoji/twemojis/1f1e8-1f1fb.png'),
  cw: require('react-native-twemoji/twemojis/1f1e8-1f1fc.png'),
  cz: require('react-native-twemoji/twemojis/1f1e8-1f1ff.png'),
  de: require('react-native-twemoji/twemojis/1f1e9-1f1ea.png'),
  dz: require('react-native-twemoji/twemojis/1f1e9-1f1ff.png'),
  ec: require('react-native-twemoji/twemojis/1f1ea-1f1e8.png'),
  eg: require('react-native-twemoji/twemojis/1f1ea-1f1ec.png'),
  es: require('react-native-twemoji/twemojis/1f1ea-1f1f8.png'),
  fr: require('react-native-twemoji/twemojis/1f1eb-1f1f7.png'),
  gb: require('react-native-twemoji/twemojis/1f1ec-1f1e7.png'),
  gh: require('react-native-twemoji/twemojis/1f1ec-1f1ed.png'),
  hr: require('react-native-twemoji/twemojis/1f1ed-1f1f7.png'),
  ht: require('react-native-twemoji/twemojis/1f1ed-1f1f9.png'),
  iq: require('react-native-twemoji/twemojis/1f1ee-1f1f6.png'),
  ir: require('react-native-twemoji/twemojis/1f1ee-1f1f7.png'),
  jo: require('react-native-twemoji/twemojis/1f1ef-1f1f4.png'),
  jp: require('react-native-twemoji/twemojis/1f1ef-1f1f5.png'),
  kr: require('react-native-twemoji/twemojis/1f1f0-1f1f7.png'),
  ma: require('react-native-twemoji/twemojis/1f1f2-1f1e6.png'),
  mx: require('react-native-twemoji/twemojis/1f1f2-1f1fd.png'),
  nl: require('react-native-twemoji/twemojis/1f1f3-1f1f1.png'),
  no: require('react-native-twemoji/twemojis/1f1f3-1f1f4.png'),
  nz: require('react-native-twemoji/twemojis/1f1f3-1f1ff.png'),
  pa: require('react-native-twemoji/twemojis/1f1f5-1f1e6.png'),
  pt: require('react-native-twemoji/twemojis/1f1f5-1f1f9.png'),
  py: require('react-native-twemoji/twemojis/1f1f5-1f1fe.png'),
  qa: require('react-native-twemoji/twemojis/1f1f6-1f1e6.png'),
  sa: require('react-native-twemoji/twemojis/1f1f8-1f1e6.png'),
  se: require('react-native-twemoji/twemojis/1f1f8-1f1ea.png'),
  sn: require('react-native-twemoji/twemojis/1f1f8-1f1f3.png'),
  tn: require('react-native-twemoji/twemojis/1f1f9-1f1f3.png'),
  tr: require('react-native-twemoji/twemojis/1f1f9-1f1f7.png'),
  us: require('react-native-twemoji/twemojis/1f1fa-1f1f8.png'),
  uy: require('react-native-twemoji/twemojis/1f1fa-1f1fe.png'),
  uz: require('react-native-twemoji/twemojis/1f1fa-1f1ff.png'),
  za: require('react-native-twemoji/twemojis/1f1ff-1f1e6.png'),
};
